# -*- coding: utf-8 -*-
"""whisper_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a4w3aGjqWd7NL2Bolz2n-IVC-PLQglfT
"""

!pip install faster-whisper
!apt-get install ffmpeg -y
!pip install pyngrok
!pip install rapidfuzz
!pip install webrtcvad
!pip install pydub

from flask import Flask, request, jsonify
from pyngrok import ngrok
from faster_whisper import WhisperModel
import webrtcvad
from pydub import AudioSegment
from pyngrok import ngrok
from rapidfuzz import fuzz, process
import re

# Set your ngrok authtoken
ngrok.set_auth_token("2wf32a56rIidEtqCvsvq6SJjetE_2iw1rtVvPCBEauk3VdWr9")

# model = WhisperModel("medium", compute_type="int8")  # Use "cpu" if needed



model = WhisperModel("medium", device = 'cuda', compute_type="int8")  # for gpu

# WebRTC VAD setup
vad = webrtcvad.Vad()
vad.set_mode(2)  # 0 = least aggressive, 3 = most aggressive

# Function: Remove silence from audio chunk

def remove_silence(audio: AudioSegment, frame_ms=30):
    audio = audio.set_channels(1).set_frame_rate(16000)
    frame_len = int(16000 * frame_ms / 1000) * 2  # bytes for 16-bit PCM mono
    raw_audio = audio.raw_data

    speech_frames = []
    for i in range(0, len(raw_audio), frame_len):
        chunk = raw_audio[i:i + frame_len]
        if len(chunk) < frame_len:
            continue
        if vad.is_speech(chunk, 16000):
            speech_frames.append(chunk)

    # Combine speech frames
    speech_audio = b"".join(speech_frames)
    output = AudioSegment(
        data=speech_audio, sample_width=2, frame_rate=16000, channels=1
    )
    return output



# def detect_vad_timestamps(audio: AudioSegment, frame_ms=30):
#     # vad = webrtcvad.Vad(3)
#     audio = audio.set_channels(1).set_frame_rate(16000)
#     raw_audio = audio.raw_data
#     frame_len = int(16000 * frame_ms / 1000) * 2  # 16-bit PCM mono = 2 bytes/sample

#     timestamps = []
#     for i in range(0, len(raw_audio), frame_len):
#         chunk = raw_audio[i:i + frame_len]
#         if len(chunk) < frame_len:
#             continue
#         if vad.is_speech(chunk, 16000):
#             start_ms = int(i / (16000 * 2) * 1000)
#             end_ms = start_ms + frame_ms
#             timestamps.append((start_ms, end_ms))

#     # Optionally merge close/overlapping speech segments
#     merged = []
#     for start, end in timestamps:
#         if merged and start <= merged[-1][1] + 10:  # merge if less than 10ms apart
#             merged[-1] = (merged[-1][0], end)
#         else:
#             merged.append((start, end))

#     return merged

# # Assume audio1 and audio2 are AudioSegment objects
# def detect_overlap(audio1, audio2):
#     # Get voice activity from each
#     vad_timestamps_A = detect_vad_timestamps(audio1)  # List of (start_ms, end_ms)
#     vad_timestamps_B = detect_vad_timestamps(audio2)

#     # Detect overlaps
#     overlaps = []
#     for a_start, a_end in vad_timestamps_A:
#         for b_start, b_end in vad_timestamps_B:
#             start = max(a_start, b_start)
#             end = min(a_end, b_end)
#             if start < end:
#                 overlaps.append((start, end))
#     return overlaps

# def remove_segments(audio, segments_to_remove):
#     clean = AudioSegment.empty()
#     last_pos = 0
#     for start, end in segments_to_remove:
#         clean += audio[last_pos:start]
#         last_pos = end
#     clean += audio[last_pos:]
#     return clean

import google.generativeai as genai

#For dual audio
app = Flask(__name__)
overlap1_path = "/tmp/prev_overlap1.wav"
overlap2_path = "/tmp/prev_overlap2.wav"

genai.configure(api_key="AIzaSyCWErdX-biF5nmjs6XifJJPqHyRju1B8yk")
model_gemini = genai.GenerativeModel("gemini-1.5-flash")
@app.route("/transcribe", methods=["POST"])
def transcribe_audio():
    if 'file1' not in request.files or 'file2' not in request.files:
        return jsonify({"error": "Both file1 and file2 are required"}), 400

    file1 = request.files['file1']
    file2 = request.files['file2']
    lan_code = request.form.get('lan_code')  # e.g., "ne" for Nepali
    TOPIC = request.form.get('prompt', 'general')  # fallback if prompt not given

    main_prompt = f"This is a conversation on {TOPIC}"
    model_task = "transcribe" if lan_code == "en" else "translate"

    # Convert uploaded files to AudioSegments
    audio1 = AudioSegment.from_file(file1)
    audio2 = AudioSegment.from_file(file2)

    if os.path.exists(overlap1_path):
        print("📎 Merging overlap...")
        prev_overlap1 = AudioSegment.from_file(overlap1_path)
        prev_overlap2 = AudioSegment.from_file(overlap2_path)

        audio1 = prev_overlap1 + audio1
        audio2 = prev_overlap2 + audio2
    # overlaps = detect_overlap(audio1, audio2)
    # audio1_clean = remove_segments(audio1, overlaps)
    audio1_silence = remove_silence(audio1)

    split_timestamp_ms = len(audio1_silence)

    # print(split_timestamp_ms)

    # audio2_clean = remove_segments(audio2, overlaps)
    audio2_silence = remove_silence(audio2)

    silence = AudioSegment.silent(duration=500)

    combined_audio = audio1_silence + silence + audio2_silence

    file_path = "/tmp/trimmed.wav"

    combined_audio.export(file_path, format="wav")
    segments, _ = model.transcribe(
        file_path,
        # initial_prompt = main_prompt,
        language=lan_code,
        task= model_task,
        vad_filter = False,
        # beam_size=1,
        # best_of=1,
        # fp16=True,
        word_timestamps=True,
        temperature=0,
        condition_on_previous_text=False
    )

    # new_overlap = combined_audio[-1000:]
    # new_overlap.export(overlap_path, format="wav")
    speaker_A_text = ""
    speaker_B_text = ""
    result = ""
    for segment in segments:
        print(f"Start: {segment.start:.2f}s, End: {segment.end:.2f}s, Text: {segment.text}")
        result += segment.text + " "
        # Convert seconds to ms and compare with split timestamp
        if segment.start * 1000 <= split_timestamp_ms:
            speaker_A_text += segment.text + " "
        else:
            speaker_B_text += segment.text + " "
    corrected_A_text = correct_transcription(speaker_A_text)
    corrected_B_text = correct_transcription(speaker_B_text)
    corrected_result = correct_transcription(result)

    total_text = "User A: " + corrected_A_text + "\nUser B: " + corrected_B_text

    gemini_prompt = f"Give me translation of the following text to hindi in a single line for each user even if it is already in that language and correct grammar but don't change the meaning:\n\n{total_text}"
    try:
        gemini_response = model_gemini.generate_content(gemini_prompt)
        english_translation = gemini_response.text
    except Exception as e:
        return jsonify({"error": str(e)}), 500

    match = re.search(r"(.*)\nUser B: (.*)", english_translation, re.DOTALL)
    user_A = match.group(1) if match else None
    user_A = user_A.strip("User A: ")
    user_B = match.group(2) if match else None

    return jsonify({"translation_A": user_B, "translation_B": user_A, "translation": corrected_result})



import re
text = "User A: This is a complete sentenc e\nUser B: And here's another one!"

match = re.search(r"(.*)\nUser B: (.*)", text, re.DOTALL)

text_before = match.group(1) if match else None
text_before = text_before.strip("User A: ")
text_after = match.group(2) if match else None

print(f"Text before User B: {text_before}")
print(f"Text after User B: {text_after}")

#For single audio

# # Create Flask app
# # translator = Translator()
# app = Flask(__name__)

# overlap_path = "/tmp/prev_overlap.wav"
# genai.configure(api_key="AIzaSyCWErdX-biF5nmjs6XifJJPqHyRju1B8yk")
# model_gemini = genai.GenerativeModel("gemini-1.5-flash")

# @app.route("/transcribe", methods=["POST"])
# def transcribe_audio():
#     if 'file' not in request.files:
#         return jsonify({"error": "No file part"}), 400

#     file = request.files['file']
#       # Receive the form data
#     lan_code = request.form.get('lan_code')  # lan_code sent via form

#     # TOPIC = request.form.get('prompt')      # prompt sent via form

#     # main_prompt = f"This is conversation on {TOPIC}"

#     model_task = "transcribe" if lan_code == "en" else "translate"

#         # Convert uploaded file to AudioSegment
#     current_audio = AudioSegment.from_file(file)

#         # 🔁 Load the previous overlap if exists
#     if os.path.exists(overlap_path):
#         print("📎 Merging overlap...")
#         prev_overlap = AudioSegment.from_file(overlap_path)
#         current_audio = prev_overlap + current_audio

#     # Remove silence
#     print("🧹 Removing silence...")
#     trimmed = remove_silence(current_audio)


#     # Save to temp file
#     file_path = "/tmp/trimmed.wav"
#     current_audio.export(file_path, format="wav")

#     segments, _ = model.transcribe(
#         file_path,
#         # initial_prompt = main_prompt,
#         language=lan_code,
#         task= model_task,
#         vad_filter = True,
#         # beam_size=1,
#         # best_of=1,
#         # fp16=True,
#         word_timestamps=False,
#         temperature=0,
#         condition_on_previous_text=False
#     )

#     new_overlap = current_audio[-1000:]
#     new_overlap.export(overlap_path, format="wav")

#     result = " ".join([segment.text for segment in segments])

#     corrected_text = correct_transcription(result)

#     # Translate to English using Gemini
#     print(result)
#     gemini_prompt = f"Give me translation of the following text to english in a single line even if it is already in that language and correct grammar but don't change the meaning:\n\n{corrected_text}"
#     try:
#         gemini_response = model_gemini.generate_content(gemini_prompt)
#         english_translation = gemini_response.text
#     except Exception as e:
#         return jsonify({"error": str(e)}), 500


#     return jsonify({"translation": corrected_text})

import os
import requests


# GIST_ID = os.environ['GIST_ID']
# GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]

GIST_ID = 'ee3f42f79c85e3f92b7e6da03830a36f'
GITHUB_TOKEN = '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'

def update_gist_ngrok_url(ngrok_url):
    api_url = f"https://api.github.com/gists/{GIST_ID}"
    headers = {"Authorization": f"token {GITHUB_TOKEN}"}
    data = {
        "files": {
            "ngrok-url.txt": {
                "content": f"{ngrok_url}"
            }
        }
    }

    response = requests.patch(api_url, headers=headers, json=data)
    if response.status_code == 200:
        print("✅ Gist updated successfully!")
    else:
        print("❌ Failed to update Gist:", response.text)

# List of names you want the model to recognize
KNOWN_NAMES = ["Ankit", "Aman", "Asmit", "Dhaubanjar", "Pokhrel", "Phuyal", "SIC", "Pulchowk" ]

COMMON_HALLUCINATIONS = [
    "thank you for watching",
    "please subscribe",
    "thanks for watching",
    "Thanks for watching!",
    "like and subscribe",
]

def correct_transcription(transcript: str, threshold: int = 60) -> str:
    for phrase in COMMON_HALLUCINATIONS:
        transcript = transcript.replace(phrase, "")
    transcript = transcript.strip()
    words = transcript.split()
    corrected_words = []

    for word in words:
        match, score, _ = process.extractOne(word, KNOWN_NAMES, scorer=fuzz.ratio)
        if score >= threshold:
            corrected_words.append(match)
        else:
            corrected_words.append(word)

    return " ".join(corrected_words)



# Open ngrok tunnel
public_url = ngrok.connect(addr=5000)
print(f"🔥 Your public URL: {public_url}")
update_gist_ngrok_url(public_url)
# Run the app
app.run(port=5000)

def remove_silence_with_timestamps(audio: AudioSegment, frame_ms=30):
    audio = audio.set_channels(1).set_frame_rate(16000)
    frame_len = int(16000 * frame_ms / 1000) * 2  # 16-bit PCM
    raw_audio = audio.raw_data

    speech_frames = []
    timestamps = []
    ms_per_frame = frame_ms
    frame_index = 0

    for i in range(0, len(raw_audio), frame_len):
        chunk = raw_audio[i:i + frame_len]
        if len(chunk) < frame_len:
            continue

        start_ms = frame_index * ms_per_frame
        end_ms = start_ms + ms_per_frame

        if vad.is_speech(chunk, 16000):
            speech_frames.append(chunk)
            timestamps.append((start_ms, end_ms))  # Keep track of this segment
        frame_index += 1

    speech_audio = b"".join(speech_frames)
    output = AudioSegment(
        data=speech_audio, sample_width=2, frame_rate=16000, channels=1
    )

    return output, timestamps

# app = Flask(__name__)
# overlap_path = "/tmp/prev_overlap.wav"

# @app.route("/transcribe", methods=["POST"])
# def transcribe_audio():
#     if 'file1' not in request.files or 'file2' not in request.files:
#         return jsonify({"error": "Both file1 and file2 are required"}), 400

#     file1 = request.files['file1']
#     file2 = request.files['file2']
#     lan_code = request.form.get('lan_code')  # e.g., "ne" for Nepali
#     TOPIC = request.form.get('prompt', 'general')  # fallback if prompt not given

#     main_prompt = f"This is a conversation on {TOPIC}"
#     model_task = "transcribe" if lan_code == "en" else "translate"

#     # Convert uploaded files to AudioSegments
#     audio1 = AudioSegment.from_file(file1)
#     audio2 = AudioSegment.from_file(file2)

#     audio1_clean, ts_audio1 = remove_silence_with_timestamps(audio1)
#     audio2_clean, ts_audio2 = remove_silence_with_timestamps(audio2)

#     # Adjust timestamps of audio2 so they start AFTER audio1
#     audio2_offset = len(audio1_clean)
#     ts_audio2_shifted = [(start + audio2_offset, end + audio2_offset) for start, end in ts_audio2]

#     combined_audio = audio1_clean + audio2_clean
#     combined_timestamps = ts_audio1 + ts_audio2_shifted


#     file_path = "/tmp/trimmed.wav"

#     combined_audio.export(file_path, format="wav")
#     segments, _ = model.transcribe(
#         file_path,
#         initial_prompt = main_prompt,
#         language=lan_code,
#         task= model_task,
#         vad_filter = True,
#         # beam_size=1,
#         # best_of=1,
#         # fp16=True,
#         word_timestamps=False,
#         temperature=0,
#         condition_on_previous_text=False
#     )


#     speaker_A_text = ""
#     speaker_B_text = ""

#     for segment in segments:
#         segment_start_ms = segment.start * 1000
#         speaker = "unknown"

#         for ts in ts_audio1:
#             if ts[0] <= segment_start_ms <= ts[1]:
#                 speaker = "A"
#                 break
#         for ts in ts_audio2_shifted:
#             if ts[0] <= segment_start_ms <= ts[1]:
#                 speaker = "B"
#                 break

#         if speaker == "A":
#             speaker_A_text += segment.text + " "
#         elif speaker == "B":
#             speaker_B_text += segment.text + " "
#     corrected_A_text = correct_transcription(speaker_A_text)
#     corrected_B_text = correct_transcription(speaker_B_text)
#     return jsonify({"translation_A": corrected_B_text, "translation_B": corrected_A_text})